services:
  memcachedcluster:
    image: memcachedcluster
    networks:
      - memcached-network
    build:
      context: .
      dockerfile: MemCachedCluster/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mcrouter

  memcached-node-1:
    image: memcached:latest
    restart: always
    container_name: memcached-node-1
    ports:
      - "11211:11211"
    command: memcached -m 128 
    networks:
      - memcached-network

  memcached-node-2:
    image: memcached:latest
    restart: always
    container_name: memcached-node-2
    ports:
      - "11212:11211"
    command: memcached -m 128 
    networks:
      - memcached-network

  memcached-node-3:
    image: memcached:latest
    restart: always
    container_name: memcached-node-3
    ports:
      - "11213:11211"
    command: memcached -m 128 
    networks:
      - memcached-network
  
  memcached-node-4:
    image: memcached:latest
    restart: always
    container_name: memcached-node-4
    ports:
      - "11214:11211"
    command: memcached -m 128 
    networks:
      - memcached-network

  mcrouter:
    image: studiosol/mcrouter:latest
    restart: always
    container_name: mcrouter
    ports:
      - "5000:5000"
    depends_on:
      - memcached-node-1
      - memcached-node-2
      - memcached-node-3
      - memcached-node-4
    networks:
      - memcached-network
    #command: mcrouter -p 5000 --config-str='{"pools":{"A":{"servers":["memcached-node-1:11211","memcached-node-2:11211"]},"B":{"servers":["memcached-node-3:11211","memcached-node-4:11211"]}},"route":{"type":"OperationSelectorRoute","default_policy":"PoolRoute|A","operation_policies":{"set":{"type":"AllSyncRoute","children":["PoolRoute|A","PoolRoute|B"]},"get":{"type":"LatestRoute","children":["PoolRoute|A","PoolRoute|B"]}}}}'
    command: mcrouter -p 5000 --config-str='{"pools":{"A":{"servers":["memcached-node-1:11211","memcached-node-2:11211","memcached-node-3:11211","memcached-node-4:11211"]}},"route":{"type":"OperationSelectorRoute","default_policy":"PoolRoute|A","operation_policies":{"set":{"type":"AllSyncRoute","children":["PoolRoute|A"]},"get":{"type":"LatestRoute","children":["PoolRoute|A"]}}}}'
    #command: mcrouter -p 5000 --config-str='{"pools":{ "A":{"servers":["memcached-node-1:11211","memcached-node-2:11211","memcached-node-3:11211","memcached-node-4:11211"]}},"route":"PoolRoute|A"}'
    volumes:
      - ./spool:/var/spool/mcrouter

networks:
  memcached-network:
    driver: bridge